//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCodeInput {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Input2022 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Input2022() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCodeInput.Input2022", typeof(Input2022).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7532
        ///37124
        ///
        ///37309
        ///
        ///7616
        ///2128
        ///2657
        ///8061
        ///8565
        ///7990
        ///5085
        ///6046
        ///7685
        ///5581
        ///
        ///35538
        ///10913
        ///
        ///5484
        ///5560
        ///4789
        ///1528
        ///4776
        ///5603
        ///5842
        ///6741
        ///4814
        ///4680
        ///5315
        ///6220
        ///1651
        ///
        ///10606
        ///12380
        ///13536
        ///12687
        ///1792
        ///5937
        ///
        ///19015
        ///
        ///6641
        ///7261
        ///4325
        ///6710
        ///3169
        ///2493
        ///4848
        ///4598
        ///1364
        ///1454
        ///7313
        ///2400
        ///
        ///34490
        ///7705
        ///
        ///1272
        ///7257
        ///10984
        ///6260
        ///3371
        ///4351
        ///4281
        ///
        ///20309
        ///12056
        ///12129
        ///
        ///4107
        ///8760
        ///3556
        ///1655
        ///9898
        ///10628
        ///10489
        ///
        ///4536
        ///2561
        ///6731
        ///6282
        ///1328
        ///3214
        ///5641
        ///3622
        ///4558
        ///1279
        ///3208
        ///1971
        ///5176 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day1 {
            get {
                return ResourceManager.GetString("Day1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to noop
        ///noop
        ///addx 6
        ///addx -1
        ///noop
        ///addx 5
        ///addx 3
        ///noop
        ///addx 3
        ///addx -1
        ///addx -13
        ///addx 17
        ///addx 3
        ///addx 3
        ///noop
        ///noop
        ///noop
        ///addx 5
        ///addx 1
        ///noop
        ///addx 4
        ///addx 1
        ///noop
        ///addx -38
        ///addx 5
        ///noop
        ///addx 2
        ///addx 3
        ///noop
        ///addx 2
        ///addx 2
        ///addx 3
        ///addx -2
        ///addx 5
        ///addx 2
        ///addx -18
        ///addx 6
        ///addx 15
        ///addx 5
        ///addx 2
        ///addx -22
        ///noop
        ///noop
        ///addx 30
        ///noop
        ///noop
        ///addx -39
        ///addx 1
        ///addx 19
        ///addx -16
        ///addx 35
        ///addx -28
        ///addx -1
        ///addx 12
        ///addx -8
        ///noop
        ///addx 3
        ///addx 4
        ///noop
        ///addx -3
        ///addx 6
        ///addx 5
        ///addx 2
        ///noop
        ///noop
        ///noop [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day10 {
            get {
                return ResourceManager.GetString("Day10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C Z
        ///C Z
        ///A Y
        ///A X
        ///C Z
        ///C Z
        ///A X
        ///C X
        ///A X
        ///C X
        ///A X
        ///A X
        ///A X
        ///A X
        ///C Y
        ///A X
        ///A X
        ///A Y
        ///C Z
        ///C X
        ///C Z
        ///C Y
        ///B Y
        ///C Y
        ///C X
        ///C X
        ///A Z
        ///C Y
        ///A Z
        ///A Z
        ///B X
        ///A Y
        ///A X
        ///B Y
        ///C X
        ///A X
        ///A X
        ///C Z
        ///C Y
        ///B X
        ///A Y
        ///C Z
        ///C Y
        ///C Z
        ///C Z
        ///A X
        ///C Z
        ///C Y
        ///C X
        ///C Z
        ///A X
        ///C Z
        ///A Y
        ///A X
        ///A X
        ///A X
        ///A X
        ///C X
        ///A X
        ///A X
        ///C X
        ///A X
        ///C Y
        ///C Y
        ///A X
        ///C Z
        ///C Y
        ///A X
        ///C Z
        ///C Y
        ///C Z
        ///C Z
        ///B X
        ///C Z
        ///C X
        ///C X
        ///B Z
        ///A X
        ///A X
        ///C Z
        ///C X
        ///C X
        ///A X
        ///A Y
        ///C X
        ///C Y
        ///A X
        ///C Z
        ///A Z
        ///C Z
        ///A Z
        ///A Z
        ///C X
        ///A X
        ///A X
        ///C Z
        ///C Y
        ///C Z
        ///A X
        ///A X
        ///C X
        ///A X
        ///C  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day2 {
            get {
                return ResourceManager.GetString("Day2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gfWpjRRQffQGCHHJsGqjsj
        ///SclzJZZvmmnPbJtVSqqNBqVCBdSCsd
        ///tlbvZJDZtmtPcJmlPnhMFQWWpMRFTfLDRRTWRp
        ///HjMPgSWjVrjgbHRRSSMRgjRdpdbGdlcdCvQfcCdlwQJfdf
        ///LNDnhtNtLNFFZDtFnhzvdldDflvvDCdlJfldpJ
        ///ZFLFZZmFtFtTNTSPRrVPWWMpRP
        ///qLBSBLRwmgzqCbzCffDlrfCV
        ///TFFFHNWFMFFMpHpGHMTHGNhrldWZCsdZsslZlZfrflDVss
        ///PTMcPGntTThHhTGctnMvSwjjvmmqLBmnjqqgCR
        ///nClJtMwwntqVVPJcgZqq
        ///mjpsDcrcSSFFPZqFBWWgVP
        ///vQcjsvhrvvrmhbmNHMNnlHbNMtCtNM
        ///bgvvhnTQtjrrrhsDDf
        ///pLSMltLzLLSjFrSSjrSJHD
        ///zNWRLBdZPllPQtCvttgCqb
        ///DRlDrrFTNDNlgzsGTBfcnqhhcnJfcrCSqc
        ///MMmm [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day3 {
            get {
                return ResourceManager.GetString("Day3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2-88,13-89
        ///12-94,12-94
        ///34-69,34-61
        ///9-76,9-9
        ///35-82,34-52
        ///9-10,10-88
        ///57-71,71-75
        ///50-71,71-91
        ///44-67,43-43
        ///68-69,67-68
        ///6-47,6-48
        ///6-52,7-67
        ///43-51,40-44
        ///56-67,57-69
        ///94-94,68-94
        ///10-97,9-9
        ///40-95,40-98
        ///22-81,22-22
        ///7-58,7-59
        ///8-82,82-82
        ///22-27,23-44
        ///5-27,7-28
        ///11-75,11-75
        ///7-90,99-99
        ///65-89,65-66
        ///24-52,29-53
        ///41-57,27-58
        ///14-95,13-26
        ///27-34,26-75
        ///18-33,33-56
        ///21-95,21-95
        ///20-29,69-71
        ///81-81,23-90
        ///47-83,47-82
        ///28-50,86-98
        ///50-76,21-50
        ///3-69,64-79
        ///17-97,10-16
        ///54-92,10-93
        ///7-75,45-77
        ///72-72,42-73 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day4 {
            get {
                return ResourceManager.GetString("Day4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to             [Q]     [G]     [M]    
        ///            [B] [S] [V]     [P] [R]
        ///    [T]     [C] [F] [L]     [V] [N]
        ///[Q] [P]     [H] [N] [S]     [W] [C]
        ///[F] [G] [B] [J] [B] [N]     [Z] [L]
        ///[L] [Q] [Q] [Z] [M] [Q] [F] [G] [D]
        ///[S] [Z] [M] [G] [H] [C] [C] [H] [Z]
        ///[R] [N] [S] [T] [P] [P] [W] [Q] [G]
        /// 1   2   3   4   5   6   7   8   9 
        ///
        ///move 1 from 2 to 6
        ///move 3 from 7 to 9
        ///move 7 from 9 to 4
        ///move 2 from 5 to 3
        ///move 3 from 2 to 8
        ///move 14 from 4 to 5
        ///move 1 from 2 to 1
        ///move 1 from 2 to 3
        ///move 3 from 6 to [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day5 {
            get {
                return ResourceManager.GetString("Day5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zcncrcnrrlccmhchssgqsqrsstfffnqfnfsswgwjjcmcnnvjvwjvwvfvnvwwhvvwmwhmwwwhbhhldhdmhhdfdbdfbdblllnfllgslllqhlhfhlhqllncnfnsffwmwzzlglzlwlhwwmvmddpvvbrvrdvrdvdhhzdhdpdzzbgbsssrpsrshrshhbqbgbmmtwwcbcrbbvnvhnncscwcwlcwlwnwswbbnwntthzzdlzdzffvqvdqvvtptdptphpddzzvhzvzwwqgqjjjvsspvspsbsffvpvcvjcvjvrvjjgmjjhrrdhhdvhvttjttzptpssnlnjjlnnhmnndjnjwwtjjtbbfflwfwgwvvpjpwpcwcgglmgmdmnmbbqtqctcwcmwwvmvlmvmdvdvhvlhlzhzttghttnvnjntnqqtmtwwhvhrhfhchqchhdrdllnwnfwfjjmsmmnhhshnhpptstjjpnpzzhmmpssgrsrzsrrffzjjhvjhjcjcpcvpccfnfjnfj [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day6 {
            get {
                return ResourceManager.GetString("Day6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $ cd /
        ///$ ls
        ///dir bqm
        ///dir ctztn
        ///dir dbclg
        ///dir fhndmnt
        ///dir gczqbh
        ///276177 hvbf.lvm
        ///dir lnsgbqp
        ///dir pblb
        ///dir pwfs
        ///209719 rtv.cjj
        ///192236 vmtnnfv.mdq
        ///dir vmvpf
        ///dir wjgh
        ///dir wjqsq
        ///$ cd bqm
        ///$ ls
        ///133711 vqv
        ///263237 wwlv.vgv
        ///$ cd ..
        ///$ cd ctztn
        ///$ ls
        ///dir gpgbfzbs
        ///dir hfvqpt
        ///55466 jshtffs
        ///dir rgzfgz
        ///115519 wdzh.szq
        ///dir wmfvclz
        ///221554 zgwwgps.gfn
        ///$ cd gpgbfzbs
        ///$ ls
        ///354710 tlvmh.ghp
        ///$ cd ..
        ///$ cd hfvqpt
        ///$ ls
        ///dir cggfgt
        ///dir jshtffs
        ///175230 nnn.chs
        ///13406 plqjpqss
        ///dir pnwcq
        ///dir str
        ///$ cd  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day7 {
            get {
                return ResourceManager.GetString("Day7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 422411333315050450444501456006152604434030162031174034546313212413064150120521030152355534203000121
        ///301324204451515335252342253126503010214314026675523135330307170405066545120014006214521335013332134
        ///410011302103513543254453460342420630261341511764171765703774273674310415535166643155002215230224343
        ///103430412453541534313620414103230457371320115213510406561165762764547335046351220043205123531400041
        ///431144033221543442550410360065613506340166441027415155772664554705330520251311025141223233351402243
        ///2133255 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day8 {
            get {
                return ResourceManager.GetString("Day8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R 1
        ///U 2
        ///R 1
        ///L 2
        ///D 2
        ///U 1
        ///R 2
        ///U 1
        ///L 2
        ///U 1
        ///D 2
        ///R 1
        ///D 1
        ///L 1
        ///U 2
        ///D 2
        ///L 2
        ///D 1
        ///U 2
        ///D 2
        ///L 1
        ///U 1
        ///L 2
        ///D 2
        ///U 2
        ///L 1
        ///U 2
        ///L 1
        ///R 2
        ///U 1
        ///L 1
        ///R 2
        ///D 1
        ///U 2
        ///R 1
        ///U 1
        ///R 2
        ///U 1
        ///R 2
        ///U 1
        ///D 1
        ///U 1
        ///D 1
        ///L 2
        ///D 2
        ///R 1
        ///U 1
        ///R 1
        ///U 1
        ///L 1
        ///U 1
        ///D 2
        ///R 2
        ///D 2
        ///L 2
        ///U 2
        ///R 1
        ///D 1
        ///U 1
        ///D 2
        ///R 1
        ///D 2
        ///L 2
        ///R 2
        ///L 1
        ///U 1
        ///L 2
        ///D 2
        ///L 2
        ///D 1
        ///R 1
        ///L 2
        ///D 2
        ///R 1
        ///L 1
        ///R 1
        ///D 1
        ///R 1
        ///D 2
        ///L 2
        ///U 1
        ///D 2
        ///R 2
        ///D 1
        ///U 1
        ///L 1
        ///D 1
        ///U 2
        ///R 1
        ///U 1
        ///L 2
        ///U 1
        ///L 1
        ///U 2
        ///L 2
        ///D 2
        ///U 1
        ///L 1
        ///U 2
        ///D 2
        ///L 2
        ///D 2
        ///R  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day9 {
            get {
                return ResourceManager.GetString("Day9", resourceCulture);
            }
        }
    }
}
