//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCodeInput {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Input2021 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Input2021() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCodeInput.Input2021", typeof(Input2021).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 195
        ///197
        ///201
        ///204
        ///203
        ///216
        ///213
        ///215
        ///216
        ///185
        ///188
        ///190
        ///205
        ///218
        ///237
        ///243
        ///248
        ///278
        ///289
        ///292
        ///304
        ///313
        ///314
        ///317
        ///329
        ///328
        ///329
        ///328
        ///329
        ///330
        ///331
        ///329
        ///333
        ///337
        ///338
        ///345
        ///352
        ///354
        ///355
        ///359
        ///360
        ///363
        ///365
        ///364
        ///370
        ///371
        ///367
        ///387
        ///403
        ///407
        ///409
        ///411
        ///416
        ///425
        ///435
        ///444
        ///445
        ///446
        ///460
        ///449
        ///454
        ///458
        ///459
        ///463
        ///464
        ///445
        ///447
        ///448
        ///450
        ///452
        ///463
        ///464
        ///475
        ///459
        ///460
        ///465
        ///477
        ///484
        ///485
        ///486
        ///498
        ///500
        ///501
        ///502
        ///516
        ///515
        ///531
        ///534
        ///560
        ///576
        ///583
        ///586
        ///587
        ///575
        ///588
        ///587
        ///591
        ///595
        ///599
        ///607
        ///608
        ///609
        ///61 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day1 {
            get {
                return ResourceManager.GetString("Day1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to forward 7
        ///down 2
        ///forward 7
        ///down 6
        ///forward 1
        ///forward 7
        ///down 3
        ///up 5
        ///forward 7
        ///forward 6
        ///down 8
        ///down 1
        ///up 5
        ///up 1
        ///down 2
        ///forward 8
        ///forward 3
        ///down 8
        ///down 9
        ///down 1
        ///forward 4
        ///down 8
        ///down 7
        ///forward 3
        ///up 5
        ///up 3
        ///forward 9
        ///forward 5
        ///forward 5
        ///down 9
        ///up 2
        ///down 4
        ///up 4
        ///down 9
        ///forward 7
        ///down 9
        ///up 7
        ///forward 4
        ///down 2
        ///down 6
        ///up 3
        ///down 2
        ///down 4
        ///up 5
        ///forward 7
        ///up 8
        ///down 4
        ///forward 8
        ///down 5
        ///forward 1
        ///forward 3
        ///up 9
        ///forward 5
        ///down 4
        ///forward 6
        ///forward 2
        ///up 3
        ///down 5
        ///down 6
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day2 {
            get {
                return ResourceManager.GetString("Day2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 000000011010
        ///011001111011
        ///100101011101
        ///000110000110
        ///101010001010
        ///010010000011
        ///011001111001
        ///100111000000
        ///011101011010
        ///000000110001
        ///101110111100
        ///111110100001
        ///000000001111
        ///001011111111
        ///101011001111
        ///101000101010
        ///110111010001
        ///000010011111
        ///000101001011
        ///101111001001
        ///100000000100
        ///010100010100
        ///100110001110
        ///101011101110
        ///111100101101
        ///000101000001
        ///001110000011
        ///111010110001
        ///101000101000
        ///011011000101
        ///000001100100
        ///101001011101
        ///001111111111
        ///101001001101
        ///100100100001
        ///101111000100
        ///00011010 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day3 {
            get {
                return ResourceManager.GetString("Day3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14,30,18,8,3,10,77,4,48,67,28,38,63,43,62,12,68,88,54,32,17,21,83,64,97,53,24,2,60,96,86,23,20,93,65,34,45,46,42,49,71,9,61,16,31,1,29,40,59,87,95,41,39,27,6,25,19,58,80,81,50,79,73,15,70,37,92,94,7,55,85,98,5,84,99,26,66,57,82,75,22,89,74,36,11,76,56,33,13,72,35,78,47,91,51,44,69,0,90,52
        ///
        ///13 62 38 10 41
        ///93 59 60 74 75
        ///79 18 57 90 28
        ///56 76 34 96 84
        ///78 42 69 14 19
        ///
        ///96 38 62  8  7
        ///78 50 53 29 81
        ///88 45 34 58 52
        ///33 76 13 54 68
        ///59 95 10 80 63
        ///
        ///36 26 74 29 55
        ///43 87 46 70 21
        /// 9 17 38 58 63
        ///56 79 8 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day4 {
            get {
                return ResourceManager.GetString("Day4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 427,523 -&gt; 427,790
        ///94,639 -&gt; 94,951
        ///757,371 -&gt; 465,663
        ///503,935 -&gt; 503,148
        ///655,565 -&gt; 655,951
        ///167,754 -&gt; 710,211
        ///634,433 -&gt; 245,433
        ///449,889 -&gt; 449,509
        ///152,753 -&gt; 207,808
        ///301,90 -&gt; 301,982
        ///566,405 -&gt; 482,405
        ///758,741 -&gt; 847,652
        ///342,686 -&gt; 921,107
        ///741,317 -&gt; 741,533
        ///976,917 -&gt; 976,664
        ///273,272 -&gt; 273,899
        ///326,616 -&gt; 326,478
        ///483,906 -&gt; 391,814
        ///20,165 -&gt; 20,349
        ///860,533 -&gt; 860,137
        ///846,834 -&gt; 846,610
        ///155,923 -&gt; 241,923
        ///989,984 -&gt; 17,12
        ///711,681 -&gt; 82,52
        ///312,788 -&gt; 312,281
        ///319,746 -&gt; 892,746
        ///5 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day5 {
            get {
                return ResourceManager.GetString("Day5", resourceCulture);
            }
        }
    }
}
