//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCodeInput {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Input2023 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Input2023() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCodeInput.Input2023", typeof(Input2023).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gtlbhbjgkrb5sixfivefivetwosix
        ///ninesixrgxccvrqscbskgzxh6cpvpxsqnb6
        ///dxxzrlzkksfsffp4
        ///sbzvmddhnjtwollnjv33d2lbcscstqt
        ///88xpnfpb
        ///ninevct4cpdvqfxmspbz9xrvxfvbpzthreesfnncrqn
        ///mqsxzsglbtmsbltrbzkbrt23
        ///seven16ninefc
        ///8jdddctvxs3
        ///fivennhhdfpmrnpjhdm2sixkrsgdt
        ///2bgkccmp2khbhmptwogsz
        ///rrddms473xcjrtsdnhp4
        ///two7eighteight29
        ///onek3three8lpfcfivenxpkhbvdm
        ///spcdsstlkr7fone1
        ///9ninejcngjshghz
        ///six78fivethreesix7fivetwo
        ///nine17bsrfbzpcr
        ///1qcdtzzfdpbcshjsjdmgsix
        ///fourtwosix3one
        ///26rqmtqznds
        ///fivefour4kmgtsplpvvvhspsjrs [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day1 {
            get {
                return ResourceManager.GetString("Day1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game 1: 4 green, 2 blue; 1 red, 1 blue, 4 green; 3 green, 4 blue, 1 red; 7 green, 2 blue, 4 red; 3 red, 7 green; 3 red, 3 green
        ///Game 2: 1 blue, 11 red, 1 green; 3 blue, 2 red, 4 green; 11 red, 2 green, 2 blue; 13 green, 5 red, 1 blue; 4 green, 8 red, 3 blue
        ///Game 3: 9 red, 2 blue; 4 blue, 2 green, 1 red; 7 red, 4 blue, 3 green; 3 blue, 6 red; 9 blue, 4 red; 3 red
        ///Game 4: 5 blue, 11 green, 3 red; 6 green, 3 blue, 7 red; 17 blue, 9 green; 1 red, 5 blue, 3 green; 6 red, 7 blue, 4 green
        ///Game 5: 3 green, 7 bl [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day2 {
            get {
                return ResourceManager.GetString("Day2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48.................501....33.....622..............763.........331.................161.683......................................980..........
        ///...491.842.....948*..................338.....*......=...........-...309.......633*....*....................*990...706...452......*..+.......
        ///...*...*....................426........*..408.........................*............659...............250.........&amp;.......*.....767...403....
        ///363.....961...959#.508*223......843.406..........690................%..479............ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day3 {
            get {
                return ResourceManager.GetString("Day3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card   1: 52 74  9  7 90 77 55 97 31 66 | 29 80 38 92 54 28 36 17 81 19 96 24 64 90 69 86 37  1 94 31 13 84 23 68 58
        ///Card   2: 19 94 92 73 38 36 84 56 77 11 | 45  2 20 81 76 48 65 42 44 71 59 39 75 37 83 29 52 78 70 87 54 64 47 63 74
        ///Card   3: 91 11 74 58 59 60 50 44  2 14 | 53 94 58 35 73 80 71  9 74 44 66 40 95 50 42 91  2 24 60 59 11 14 37  5 45
        ///Card   4: 65 93 62 18 29 95  8 79 60 16 | 78 62 68  4 96  8 57 95 79 75 72 60 74 16 55 39 76 71 65 18 53 93 28 90 29
        ///Card   5: 98 19 69 18 44 42 74  8 64 90  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day4 {
            get {
                return ResourceManager.GetString("Day4", resourceCulture);
            }
        }
    }
}
