//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCodeInput {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Input2021 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Input2021() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCodeInput.Input2021", typeof(Input2021).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 195
        ///197
        ///201
        ///204
        ///203
        ///216
        ///213
        ///215
        ///216
        ///185
        ///188
        ///190
        ///205
        ///218
        ///237
        ///243
        ///248
        ///278
        ///289
        ///292
        ///304
        ///313
        ///314
        ///317
        ///329
        ///328
        ///329
        ///328
        ///329
        ///330
        ///331
        ///329
        ///333
        ///337
        ///338
        ///345
        ///352
        ///354
        ///355
        ///359
        ///360
        ///363
        ///365
        ///364
        ///370
        ///371
        ///367
        ///387
        ///403
        ///407
        ///409
        ///411
        ///416
        ///425
        ///435
        ///444
        ///445
        ///446
        ///460
        ///449
        ///454
        ///458
        ///459
        ///463
        ///464
        ///445
        ///447
        ///448
        ///450
        ///452
        ///463
        ///464
        ///475
        ///459
        ///460
        ///465
        ///477
        ///484
        ///485
        ///486
        ///498
        ///500
        ///501
        ///502
        ///516
        ///515
        ///531
        ///534
        ///560
        ///576
        ///583
        ///586
        ///587
        ///575
        ///588
        ///587
        ///591
        ///595
        ///599
        ///607
        ///608
        ///609
        ///61 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day1 {
            get {
                return ResourceManager.GetString("Day1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (({({({(({{&lt;{{()&lt;&gt;}}&gt;}}([&lt;[(&lt;&gt;{})(()()))[[{}[]]{&lt;&gt;{}}]&gt;(&lt;(&lt;&gt;[])&lt;[]()&gt;&gt;&lt;[{}[]]([]&lt;&gt;)&gt;)]{{({{}[]}{{}{}})}})
        ///[{(&lt;(&lt;&lt;([[[{(([]{})&lt;(){}&gt;)&lt;{&lt;&gt;}(()[])&gt;}]]{[([(()[])[[][]]]&lt;((){})((){})&gt;)({{{}[]}&lt;{}&gt;})]}]){{[[&lt;&lt;{&lt;&gt;}(&lt;
        ///((&lt;[([(({&lt;&lt;&lt;{{&lt;&gt;&lt;&gt;}({}&lt;&gt;)}{{&lt;&gt;{}}[[]()]}&gt;&gt;([&lt;[{}{}]&gt;{[()&lt;&gt;]&lt;&lt;&gt;()&gt;}]&lt;(&lt;{}()&gt;&lt;[]{}&gt;)&lt;&lt;[]&lt;&gt;&gt;}&gt;)&gt;}[&lt;{&lt;([&lt;&gt;&lt;&gt;]&lt;
        ///[&lt;[&lt;({{({{[({[[][]]&lt;{}&lt;&gt;&gt;})&lt;[&lt;{}{}&gt;]([&lt;&gt;&lt;&gt;](&lt;&gt;{}))&gt;]{[{[[]{}}{{}{}}}&lt;(&lt;&gt;&lt;&gt;)({})&gt;]{({()()}[&lt;&gt;()])
        ///[&lt;{&lt;&lt;({[{{{(&lt;({}()){{}[]}&gt;&lt;(&lt;&gt;&lt;&gt;)[[]{}]&gt;)}&lt;(([{}{}]{&lt;&gt;[]}))&lt;(&lt;&lt;&gt;[]&gt;){&lt;[]&gt;(&lt;&gt;{})}&gt;&gt;}({{((&lt;&gt;())&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day10 {
            get {
                return ResourceManager.GetString("Day10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5723573158
        ///3154748563
        ///4783514878
        ///3848142375
        ///3637724151
        ///8583172484
        ///7747444184
        ///1613367882
        ///6228614227
        ///4732225334.
        /// </summary>
        public static string Day11 {
            get {
                return ResourceManager.GetString("Day11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VJ-nx
        ///start-sv
        ///nx-UL
        ///FN-nx
        ///FN-zl
        ///end-VJ
        ///sv-hi
        ///em-VJ
        ///start-hi
        ///sv-em
        ///end-zl
        ///zl-em
        ///hi-VJ
        ///FN-em
        ///start-VJ
        ///jx-FN
        ///zl-sv
        ///FN-sv
        ///FN-hi
        ///nx-end.
        /// </summary>
        public static string Day12 {
            get {
                return ResourceManager.GetString("Day12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 43,593
        ///1139,385
        ///1178,51
        ///216,679
        ///743,185
        ///1241,250
        ///197,60
        ///479,700
        ///565,845
        ///1022,330
        ///744,714
        ///440,535
        ///137,81
        ///35,766
        ///482,249
        ///1120,280
        ///484,98
        ///301,823
        ///928,616
        ///601,7
        ///60,835
        ///1092,371
        ///1033,584
        ///1079,833
        ///44,665
        ///469,777
        ///915,526
        ///759,290
        ///843,891
        ///1225,464
        ///326,831
        ///723,333
        ///1099,362
        ///962,285
        ///1069,474
        ///315,731
        ///716,506
        ///741,430
        ///1228,320
        ///1099,878
        ///485,522
        ///328,333
        ///1289,432
        ///1173,506
        ///395,526
        ///47,625
        ///1155,273
        ///114,856
        ///914,826
        ///1263,849
        ///1294,693
        ///607,289
        ///1225,138
        ///25,519
        ///1051,564
        ///738,747
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day13 {
            get {
                return ResourceManager.GetString("Day13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to forward 7
        ///down 2
        ///forward 7
        ///down 6
        ///forward 1
        ///forward 7
        ///down 3
        ///up 5
        ///forward 7
        ///forward 6
        ///down 8
        ///down 1
        ///up 5
        ///up 1
        ///down 2
        ///forward 8
        ///forward 3
        ///down 8
        ///down 9
        ///down 1
        ///forward 4
        ///down 8
        ///down 7
        ///forward 3
        ///up 5
        ///up 3
        ///forward 9
        ///forward 5
        ///forward 5
        ///down 9
        ///up 2
        ///down 4
        ///up 4
        ///down 9
        ///forward 7
        ///down 9
        ///up 7
        ///forward 4
        ///down 2
        ///down 6
        ///up 3
        ///down 2
        ///down 4
        ///up 5
        ///forward 7
        ///up 8
        ///down 4
        ///forward 8
        ///down 5
        ///forward 1
        ///forward 3
        ///up 9
        ///forward 5
        ///down 4
        ///forward 6
        ///forward 2
        ///up 3
        ///down 5
        ///down 6
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day2 {
            get {
                return ResourceManager.GetString("Day2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 000000011010
        ///011001111011
        ///100101011101
        ///000110000110
        ///101010001010
        ///010010000011
        ///011001111001
        ///100111000000
        ///011101011010
        ///000000110001
        ///101110111100
        ///111110100001
        ///000000001111
        ///001011111111
        ///101011001111
        ///101000101010
        ///110111010001
        ///000010011111
        ///000101001011
        ///101111001001
        ///100000000100
        ///010100010100
        ///100110001110
        ///101011101110
        ///111100101101
        ///000101000001
        ///001110000011
        ///111010110001
        ///101000101000
        ///011011000101
        ///000001100100
        ///101001011101
        ///001111111111
        ///101001001101
        ///100100100001
        ///101111000100
        ///00011010 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day3 {
            get {
                return ResourceManager.GetString("Day3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14,30,18,8,3,10,77,4,48,67,28,38,63,43,62,12,68,88,54,32,17,21,83,64,97,53,24,2,60,96,86,23,20,93,65,34,45,46,42,49,71,9,61,16,31,1,29,40,59,87,95,41,39,27,6,25,19,58,80,81,50,79,73,15,70,37,92,94,7,55,85,98,5,84,99,26,66,57,82,75,22,89,74,36,11,76,56,33,13,72,35,78,47,91,51,44,69,0,90,52
        ///
        ///13 62 38 10 41
        ///93 59 60 74 75
        ///79 18 57 90 28
        ///56 76 34 96 84
        ///78 42 69 14 19
        ///
        ///96 38 62  8  7
        ///78 50 53 29 81
        ///88 45 34 58 52
        ///33 76 13 54 68
        ///59 95 10 80 63
        ///
        ///36 26 74 29 55
        ///43 87 46 70 21
        /// 9 17 38 58 63
        ///56 79 8 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day4 {
            get {
                return ResourceManager.GetString("Day4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 427,523 -&gt; 427,790
        ///94,639 -&gt; 94,951
        ///757,371 -&gt; 465,663
        ///503,935 -&gt; 503,148
        ///655,565 -&gt; 655,951
        ///167,754 -&gt; 710,211
        ///634,433 -&gt; 245,433
        ///449,889 -&gt; 449,509
        ///152,753 -&gt; 207,808
        ///301,90 -&gt; 301,982
        ///566,405 -&gt; 482,405
        ///758,741 -&gt; 847,652
        ///342,686 -&gt; 921,107
        ///741,317 -&gt; 741,533
        ///976,917 -&gt; 976,664
        ///273,272 -&gt; 273,899
        ///326,616 -&gt; 326,478
        ///483,906 -&gt; 391,814
        ///20,165 -&gt; 20,349
        ///860,533 -&gt; 860,137
        ///846,834 -&gt; 846,610
        ///155,923 -&gt; 241,923
        ///989,984 -&gt; 17,12
        ///711,681 -&gt; 82,52
        ///312,788 -&gt; 312,281
        ///319,746 -&gt; 892,746
        ///5 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day5 {
            get {
                return ResourceManager.GetString("Day5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,2,1,1,1,1,1,1,2,1,3,1,1,1,1,3,1,1,1,5,1,1,1,4,5,1,1,1,3,4,1,1,1,1,1,1,1,5,1,4,1,1,1,1,1,1,1,5,1,3,1,3,1,1,1,5,1,1,1,1,1,5,4,1,2,4,4,1,1,1,1,1,5,1,1,1,1,1,5,4,3,1,1,1,1,1,1,1,5,1,3,1,4,1,1,3,1,1,1,1,1,1,2,1,4,1,3,1,1,1,1,1,5,1,1,1,2,1,1,1,1,2,1,1,1,1,4,1,3,1,1,1,1,1,1,1,1,5,1,1,4,1,1,1,1,1,3,1,3,3,1,1,1,2,1,1,1,1,1,1,1,1,1,5,1,1,1,1,5,1,1,1,1,2,1,1,1,4,1,1,1,2,3,1,1,1,1,1,1,1,1,2,1,1,1,2,3,1,2,1,1,5,4,1,1,2,1,1,1,3,1,4,1,1,1,1,3,1,2,5,1,1,1,5,1,1,1,1,1,4,1,1,4,1,1,1,2,2,2,2,4,3,1,1,3,1,1,1,1,1,1,2,2,1,1,4, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day6 {
            get {
                return ResourceManager.GetString("Day6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1101,1,29,67,1102,0,1,65,1008,65,35,66,1005,66,28,1,67,65,20,4,0,1001,65,1,65,1106,0,8,99,35,67,101,99,105,32,110,39,101,115,116,32,112,97,115,32,117,110,101,32,105,110,116,99,111,100,101,32,112,114,111,103,114,97,109,10,720,75,471,1142,1442,166,896,138,61,643,1331,315,365,43,4,289,577,1249,30,53,117,956,28,385,27,168,92,110,127,331,27,93,730,122,27,19,1563,708,849,190,1620,1135,878,74,60,424,500,10,7,1687,375,159,566,228,1069,1603,194,463,387,2,890,1060,600,27,578,66,91,510,383,827,1485,18,30,500,0,386,108 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day7 {
            get {
                return ResourceManager.GetString("Day7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to daegb gadbcf cgefda edcfagb dfg acefbd fdgab fg bdcfa fcgb | cdfgba fgbc dbfac gfadbc
        ///bdfc dcbegf bf egfbcda gebad cfgaed bfe edfgc aegfcb gebdf | fb fb bcdfaeg fcgdeb
        ///cebdgaf bfcd gceab bf bfcea gceafd ecdfa fegdab bfcade fba | dfcb dagfbe fbaged bfa
        ///efabcg aegcdb fgaed fac dgafbc becf eadcgbf aegfc fc cagbe | ecgfa agdef eagfc gdceab
        ///fcdae cdeabf fga gf gabfde cgadb gadebfc cgfe aegcdf afgcd | fbgadce gadefb fag bafegd
        ///gecadbf bgc dacgf gaecbf cbeda dbfg bgdca bg bafcgd gdacef | cdgfa fceabg dgfb dga [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day8 {
            get {
                return ResourceManager.GetString("Day8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8656456789432129876532356789899998754320146789767893213468953205459323997678901997655423567797655667
        ///6545345996543234987321567896798749886531235697657999304989764312378999886567899876543212345679543156
        ///5431239879694349876432398945976532997782356789547898919898765434567988765456789997654323456789654345
        ///6520139768989556987543499239854321098993768996536587998789876597679876544245690198965654567899875456
        ///7631297657679697998756789349765432129654879797627456789678997698789997432136789999876765698969987887
        ///97 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Day9 {
            get {
                return ResourceManager.GetString("Day9", resourceCulture);
            }
        }
    }
}
